---
funtional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-funtional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Пользователь должен иметь возможность удалять добавленные товары из корзины
  - Пользователь должен иметь возможность добавить товар в корзину и продолжить выбирать товары в каталоге
  - Пользователь должен иметь возможность заказавать товары, которые были добавлены в корзину